### ISSUE TITLE
Integration test setup

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/akeneo-csharp#1]
The integration test suite actually calls the PIM to add/update/remove resources.

Normally, that would be fine; we could use some sort of test fixture setup that add expected products to the PIM and then a corresponding tear down that removes them. However the current API only allows for removal of products (and not categories, families etc).

Some work need to be done to retrieve the client id and secret from the PIM instance used in the tests. It should be done programmatically on an instance that is setup during test start.

**Comment by ahocquard** [comment]
Three possible strategies when you test an API from my point of view : 
- mock everything
- use a docker image with an installation of the fixtures. Before each test you can launch a new instance of your docker. 
- do both of the previous strategies :)

For the client_id and secret_id, I agree it is complex to get them. But it's for security purposes and so, you have to do it programmatically (if you are using a docker, not needed with mock).

Do not hesitate if you have more questions/comments :)

**Comment by pardahlman** [comment]
Hello @ahocquard 👋 thanks for your input!

I've written a few API clients for different systems, and my experience is that only relying on mocked responses only takes you so far. Some instances I found it to be problematic is:

* If the API contract changes, rendering the client useless, but all tests are green due to mocked responses 
* If the API does not behave as I thought it would (like what I experienced in https://github.com/akeneo/pim-community-dev/issues/6060 and https://github.com/akeneo/pim-docs/issues/560)
* When optimizing performance by modifying batch-size, concurrency etc.

Let's just say I'd be happier if I got automatic confirmation that the client worked with the actual API 😄 

I've done some reading about [Docker.DotNet](https://github.com/Microsoft/Docker.DotNet) that I might be able to use in a Test Fixutre Setup to create a new docker container with Akeneo in it. It looks promising 👍 . I should be able to call `exec` on the newly created container to get the client id and secret. String parsing isn't my favorite approach, but if this PR gets accepted I think I'm all set: https://github.com/akeneo/pim-community-dev/pull/6084

Thanks again for taking the time!

**Comment by ahocquard** [comment]
Hi @pardahlman,

Totally agree on the mock part. Moreover, with stream, you can experience some weird issues (timeout, apache config) like you said.

But mocks can be useful too to detect problems with thread safety in batch for example. Or not if the thread safety problem is about your HTTP client ;) 

Take care : the fixtures can change from a PIM version to another one (1.7 / 1.8), and then impact your tests. Maybe a subject to address.

I really think a mix of mocks and real tests is the best thing, but it needs more maintenance.

**Comment by pardahlman** [comment]
sounds like we're on the same page, @ahocquard. I'll let you know how it goes in a not to long future ;)
