### ISSUE TITLE
Does it take in account deletion of a property with a patch ?

### ISSUE THREAD

**Issue by ahocquard** [pardahlman/akeneo-csharp#16]
Hi @pardahlman,

I don't know .NET (at all), so, sorry if I'm wrong!
I see that line in the serialiazer : https://github.com/pardahlman/akeneo-csharp/blob/master/Akeneo/Serialization/AkeneoSerializerSettings.cs#L17

I suppose it ignores null values in an object no ?
If it's the case, it would be impossible to delete a variant group of an existing product with a patch.

```
PATCH api/rest/v1/products/id_01

{
    "variant_group": null
}
```

Of course, it works with any nullable properties to delete a property (parent of a category for example).

**Comment by pardahlman** [comment]
@ahocquard - thanks for raising the question! I think you are right, but I'd like to ask some follow-up questions on the topic. Let me get back to you in a few days!

**Comment by pardahlman** [comment]
Hello again, @ahocquard 

I've played around with the API and here's the current take on the payload I'm sending:

1. If a property is null, like `variant_group` in your example, but also in patching scenarios of product values like the once in the [documentation](https://api.akeneo.com/documentation/update.html#update-behavior), null is passed to the API so that values can be removed.
2. When creating a new product, if no explicit value is provided for the array properties (like `values`, `association` etc) an empty array is passed along as property value (previously entire property was omitted)

Does this make sense to you? Can you think of any other "null related" scenarios that I need to consider? 🙂 

Do I understand correctly that there is no way to remove an attribute from a product all together, the only thing I can remove is the attributes value?

**Comment by ahocquard** [comment]
Hi @pardahlman, 

From what you are saying I don't know if it behaves correctly. Let me describe it more precisely.
Imagine you have an attribute with variant group_group `foo` and family `bar`.
Your simplified product will be: 
```
{
  "code":"my_code",
  "variant_group":"foo",
  "family":"bar"
}
```

Now, if you want to delete the variant group, you should do this request:
```
PATCH api/rest/v1/products/my_code

{
    "variant_group": null
}
```
 You should not be forced to GET the product before doing this operation. After all, you are not using the other value `family`, just deleting `variant_group` value.

So, it could be complicated to know in an object Product if the property `variant_group` has null value due to the initialisation of the object or because you are setting it at null intentionally.

But it seems to work differently between Java and .NET.
In java: 
```
Product product = new Product();
System.out.println(product.getVariantGroup()); // print null but because it's a new object, but should not be displayed in the serialised JSON
product.setVariantGroup(null);
System.out.println(product.getVariantGroup()); // print null but because you set it manually, and should be displayed in the serialised JSON to delete the value
```

So, you see in the example above that it's complicated to know when serialising the object if it's null intentionally or not.

**Comment by pardahlman** [comment]
@ahocquard I see what you are saying. It is problematic as null is the default value of an unassigned reference type, but if explicitly set to null it should be passed to the API.

I understand that you are writing a PHP client, too... I'm guessing that you will run into a similar problem in that client. Do you know how you plan to  solve it?

**Comment by ahocquard** [comment]
@pardahlman We will use array in PHP. It's in the DNA of the language and not surprising. Also, it means far less coupling between the client and the server too.
For example, adding a property in a resource = 0 maintenance with array. Not the case with object (you have to add the property in the object).
And the goal of an API is to avoid coupling between client server, so let's use array in PHP.

But we tried with object too and that's why I've seen that problem ;) And object is not an option in Java or .NET, because these languages are fully OOP.

There are some solutions, but unfortunately I don't know the best one.

1. Use a kind of constant when setting with null. Because the "null" value of an unassigned  reference type is actually not

 the same value as a "null" of an assigned reference type.

2. I've seen that in Java, you have Optional now (https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html). Don't know if it exists in .NET, I don't think so.

3. use a list of modified properties in the object. Then , when you are serialising, the object know which properties that should be in the JSON. 
But it implies to use different objects:

-  object used by the serialiser when setting the value in a GET request. The properties are not considered modified in that case.
- object used by the user. Each modified property should be registered in that case.

I've searched a design pattern but without any success. I think that it's because PATCH is generally not used so much. With PUT, you don't have this problem, and it's the default verb in REST when updating. Not very useable in the PIM context though.

**Comment by pardahlman** [comment]
@ahocquard - thanks for letting me know. I guess it almost becomes a philosophical question at this point, the array solution indeed decouples the client from the api, but it does not give the end user the same effortless usage of the client as you would need to know what the expected property names are 🙂 

I've been thinking along the line of your suggestion, but right now I'm leaning toward using .NET's [dynamic object](https://msdn.microsoft.com/en-us/library/system.dynamic.dynamicobject(v=vs.110).aspx). 

```csharp
client.UpdateAsync<Product>("product_id", new { variant_group : null});
```
I'll try it out and let you know how it goes!

**Comment by ahocquard** [comment]
@pardahlman yep, it really depends of the philosophy of the language. Array are so convenient in PHP (it's almost JSON), it will be easy to manipulate just by reading the documentation. Same in JS (because it's directly JSON ;) ).

And it offers the possibility to implement object "client" using the "array" client by composition (one package using another one). Then you would have 2 clients : object client + array client.

In Java, you have List (numerical array of PHP) and Map (associative array of PHP), it's far less convenient to generate a JSON ! You had to implement it with object. I would choose Java 8 Optional I think.

I don't know how to handle it in .NET properly : do your best ;)

**Comment by pardahlman** [comment]
@ahocquard perhaps I'm missing something... but, I think it is strange that when I create a product, if I omit properties like `variant_group`  the API silently ignores it and falls back to some default (like "no variant group"). However, if I omit `locale` or `scope` from an entry in the `values` array, the API complains that it is not present. I think it would make sense if if was interpreted the same way as if null was provided for these values.

**Comment by pardahlman** [comment]
@ahocquard added documentation about the update behaviour: http://akeneonet.readthedocs.io/en/latest/updating-resources.html

care to read and give your input on it?

**Comment by ahocquard** [comment]
Hello @pardahlman I was pretty busy but I will try to read it this week and give a feedback :)

**Comment by ahocquard** [comment]
Hello @pardahlman and sorry for the delay.

The documentation is clear.
I don't understand the sentence "This approach requires no extra round-trip, but gives the caller greater greater responsibility." in "Delete values" chapter, could you explain me why ?

Btw, good job for the documentation 👍

**Comment by ahocquard** [comment]
Hello, I think we can close this discussion :)
