### ISSUE TITLE
Correct serializer not passed in ProductValueDataConverter

### ISSUE THREAD

**Issue by enrique-avalon** [pardahlman/akeneo-csharp#19]
When calling ToObject on JArray the correctly configured serializer isn't passed as parameter. Instead default serializer settings are used where NullValueHandling isn't set to ignore and an exception will be thrown if the serializer stumples upon a null for a value type.

**Comment by pardahlman** [comment]
The PR has been merged and a pre-release (`0.1.15-dev-00048`) is [available at NuGet](https://www.nuget.org/packages/Akeneo.NET/0.1.15-dev-00048) 👍
