### ISSUE TITLE
Complete list of Locales

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/akeneo-csharp#6]
Locales are modeled as strings, and there is a [helper class](https://github.com/pardahlman/akeneo-csharp/blob/master/Akeneo/Model/Locales.cs) that lists "all" available locales. However, this list is far from complete

```csharp
public class Locales
{
    public const string SwedenSwedish = "sv_SE";
    public const string EnglishUs = "en_US";
}
```

It should contain all valid locales

**Comment by objecta** [comment]
var locales = CultureInfo.GetCultures(CultureTypes.AllCultures)
                .Where(c => !string.IsNullOrEmpty(c.Name) && !c.IsNeutralCulture)
                .Select(c => new { Region = new RegionInfo(c.Name), Parent = c.Parent.EnglishName.Replace(" ", "") })
                .Select(s => new { Culture = s.Region.Name, Country = s.Parent, Region = s.Region.EnglishName })
                .OrderBy(s => s.Region)
                .Distinct()
                .Select(s => $"public const string {s.Country.Replace(" ","").Replace("(", "").Replace(")", "")}{s.Region.Replace(" ", "").Replace("(", "").Replace(")", "")} = \"{s.Culture.Replace(" ", "")}\";").ToArray();

            File.WriteAllLines(@"d:\temp\localesList.txt", locales);

**Comment by pardahlman** [comment]
Thanks for this, @objecta - feel free to submit a PR 👌
