### ISSUE TITLE
Complete list of Currencies

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/akeneo-csharp#7]
Currencies are modeled as strings. There is a [helper class](https://github.com/pardahlman/akeneo-csharp/blob/master/Akeneo/Model/Currency.cs) that keeps valid currency values. It is suppose to hold all valid currencies, but is far from complete

```csharp
public class Currency
{
    public const string SEK = "SEK";
    public const string EUR = "EUR";
    public const string USD = "USD";
}
```

**Comment by objecta** [comment]
var currencySymbols = CultureInfo.GetCultures(CultureTypes.AllCultures)
                .Where(c => !string.IsNullOrEmpty(c.Name) && !c.IsNeutralCulture)
                .Select(c => new RegionInfo(c.Name)).Select(s => s.ISOCurrencySymbol).OrderBy(s => s).Distinct()
                .Select(s => $"public const string {s} = \"{s}\";").ToArray();

            File.WriteAllLines(@"d:\temp\currencyList.txt", currencySymbols);

**Comment by pardahlman** [comment]
Hey @objecta - thanks for this. Feel free to submit a PR 👌
